In [1]:
import numpy as np

In [2]:
array = [[1,2,3], [4,5,6], [7,8,9]]
#turn array into 2d 
#3 rows and 3 columns
np.array(array)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
#Numpy built in functions
#start, stop, step
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
#tuple rows/columns
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
#start, stop, spacing
#10 evenly spaced points between 0-5
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [7]:
#create an identity matrix 4x4
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
#one dimensional array filled with random numbers
np.random.rand(5)


array([0.91439697, 0.38968308, 0.15640122, 0.89381324, 0.232111  ])

In [9]:
#5x5 array filled with random numbers
#uniform distribution between 0-1
np.random.rand(5,5)

array([[0.42106613, 0.10349105, 0.00231039, 0.66175595, 0.17347969],
       [0.80317276, 0.59884989, 0.61408317, 0.74341086, 0.67554497],
       [0.54593321, 0.51458194, 0.86630504, 0.26070785, 0.36471157],
       [0.77454518, 0.46236049, 0.93677849, 0.60846078, 0.99671733],
       [0.83208516, 0.17555458, 0.86994957, 0.17478632, 0.13240688]])

In [10]:
# uniform distribution surounded by 0
np.random.randn(2)

array([-0.39663212, -0.05822111])

In [11]:
np.random.randn(4,4)


array([[-0.32253373, -0.78172913, -1.42842378, -0.84326868],
       [-0.30353509,  0.68808183, -1.20397812, -0.85172593],
       [ 1.35223683, -1.36581818, -0.5764415 ,  1.24165246],
       [ 0.9910039 , -1.27146647,  1.45393088, -0.12967396]])

In [12]:
#random integer between 1 and 99
np.random.randint(1, 100)

60

In [13]:
# inclusive lowend exclusive high end
np.random.randint(1, 100 , 10)

array([35,  6, 77, 65, 81, 19, 85, 52, 69, 34])

In [14]:
ranarr = np.random.randint(0,50,10)
ranarr 

array([13,  6, 21, 26, 29, 49, 15, 19,  5, 35])

In [15]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
# must have 5 x 5 = 25 elements in the array
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
ranarr.min()

5

In [18]:
ranarr.max()

49

In [19]:
#find the index of max
ranarr.argmax()

5

In [20]:
ranarr.argmin()

8

In [21]:
arr.shape

(25,)

In [22]:
arr.dtype

dtype('int64')

In [39]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [24]:
slice_of_array = arr[0:5]
slice_of_array

array([0, 1, 2, 3, 4])

In [25]:
# changes original array
slice_of_array[:] = 99
slice_of_array

array([99, 99, 99, 99, 99])

In [26]:
arr_copy = arr.copy()
arr_copy 

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [27]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
#double bracket format to index
# row/column
arr_2d[0][0]

5

In [29]:
arr_2d[2][2]

45

In [30]:

#or
arr_2d[2,2]
arr_2d


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
# Grab rows 0 and 1 (do not include 2)
# in column 0-1
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [32]:
arr_2d[1:3,1:]

array([[25, 30],
       [40, 45]])

In [33]:
arr = np.arange(1,11)
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [35]:
# Shows values that are true
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [36]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [37]:
# [13,14
#  23,24]
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [38]:
#6. Numpy Operations @ -1:27

In [41]:
# Basic arithmetic with np arrays
arr * 2
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [44]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [45]:
np.max(arr)

10

In [46]:
np.min(arr)

0

In [47]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])